version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-12-07T00-00-00Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  server:
    build: ./apps/server
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/app?schema=public
      JWT_SECRET: devsecret
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_BUCKET: videos
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
      - minio

volumes:
  dbdata:
  miniodata:
