
version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lumi
      POSTGRES_PASSWORD: lumi
      POSTGRES_DB: lumi
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
  api:
    build: ./backend
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://lumi:lumi@db:5432/lumi?schema=public
      JWT_SECRET: supersecret_change_me
      PORT: 4000
      CORS_ORIGIN: http://localhost:8080,http://localhost:4000
      UPLOAD_STRATEGY: local
      UPLOAD_DIR: /app/public/uploads
      BASE_URL: http://localhost:4000
      PROFANITY_FILTER: "on"
      MODERATION_AI_THRESHOLD: "0.8"
      VAPID_PUBLIC_KEY: ""
      VAPID_PRIVATE_KEY: ""
      VAPID_SUBJECT: "mailto:admin@example.com"
    ports: ["4000:4000"]
    volumes:
      - ./backend:/app
      - uploads:/app/public/uploads
    command: sh -c "npx prisma db push && node dist/index.js"
  frontend:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
volumes: { db_data: {}, uploads: {} }
